# Generated by Django 5.2 on 2025-06-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="average_rating",
            field=models.FloatField(default=0.0),
        ),
    ]
