# Generated by Django 5.2 on 2025-06-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_average_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="likes_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
